// lib/words_06.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_06: Word[] = [
  { kanji: "編む", hiragana: "あむ", meaning: "엮다, 뜨다" },
  { kanji: "栄養", hiragana: "えいよう", meaning: "영양" },
  { kanji: "演奏", hiragana: "えんそう", meaning: "연주" },
  { kanji: "香り", hiragana: "かおり", meaning: "향기" },
  { kanji: "隠す", hiragana: "かくす", meaning: "감추다, 숨기다" },
  { kanji: "観察", hiragana: "かんさつ", meaning: "관찰" },
  { kanji: "興味", hiragana: "きょうみ", meaning: "흥미" },
  { kanji: "盛んだ", hiragana: "さかんだ", meaning: "번창하다" },
  { kanji: "順番", hiragana: "じゅんばん", meaning: "순번, 차례" },
  { kanji: "代表的だ", hiragana: "だいひょうてきだ", meaning: "대표적이다" },
  { kanji: "戦う", hiragana: "たたかう", meaning: "싸우다, 전투하다" },
  { kanji: "防ぐ", hiragana: "ふせぐ", meaning: "방어하다, 막다" },
  { kanji: "守る", hiragana: "まもる", meaning: "지키다" },
  { kanji: "文句", hiragana: "もんく", meaning: "불평, 불만" },
  { kanji: "破れる", hiragana: "やぶれる", meaning: "찢어지다, 깨지다" },
  { kanji: "リサイクル", hiragana: "", meaning: "리사이클, 재활용" },
  { kanji: "料金", hiragana: "りょうきん", meaning: "요금" },
  { kanji: "割合", hiragana: "わりあい", meaning: "비율" },
  { kanji: "あきる", hiragana: "", meaning: "질리다, 싫증나다" },
  { kanji: "穴", hiragana: "あな", meaning: "구멍" },
  { kanji: "印象", hiragana: "いんしょう", meaning: "인상" },
  { kanji: "お祝い", hiragana: "おいわい", meaning: "축하, 축하선물" },
  { kanji: "我慢", hiragana: "がまん", meaning: "참음" },
  { kanji: "間隔", hiragana: "かんかく", meaning: "간격" },
  { kanji: "記念", hiragana: "きねん", meaning: "기념" },
  { kanji: "くせ", hiragana: "", meaning: "버릇, 습관" },
  { kanji: "悔しい", hiragana: "くやしい", meaning: "분하다" },
  { kanji: "合計", hiragana: "ごうけい", meaning: "합계" },
  { kanji: "覚める", hiragana: "さめる", meaning: "깨다, 눈이 뜨이다" },
  { kanji: "資源", hiragana: "しげん", meaning: "자원" },
  { kanji: "積極的", hiragana: "せっきょくてき", meaning: "적극적" },
  { kanji: "当日", hiragana: "とうじつ", meaning: "당일" },
  { kanji: "パンフレット", hiragana: "", meaning: "팸플릿, 소책자" },
  { kanji: "ぶつける", hiragana: "", meaning: "부딪치다, 맞부딪치다" },
  { kanji: "ふらふら", hiragana: "", meaning: "비틀비틀" },
  { kanji: "方法", hiragana: "ほうほう", meaning: "방법" },
  { kanji: "目標", hiragana: "もくひょう", meaning: "목표" },
  { kanji: "~料", hiragana: "りょう", meaning: "료, ~료" },
  { kanji: "分ける", hiragana: "わける", meaning: "나누다, 분배하다" },
  { kanji: "噂", hiragana: "うわさ", meaning: "소문" },
  { kanji: "追いつく", hiragana: "おいつく", meaning: "따라잡다" },
  { kanji: "おかしい", hiragana: "", meaning: "이상하다" },
  { kanji: "おぼれる", hiragana: "", meaning: "빠지다" },
  { kanji: "主に", hiragana: "おもに", meaning: "주로" },
  { kanji: "渇く", hiragana: "かわく", meaning: "마르다, 건조하다" },
  { kanji: "交換", hiragana: "こうかん", meaning: "교환" },
  { kanji: "材料", hiragana: "ざいりょう", meaning: "재료" },
  { kanji: "自慢", hiragana: "じまん", meaning: "자랑" },
  { kanji: "渋滞", hiragana: "じゅうたい", meaning: "정체, 밀림" },
  { kanji: "たたむ", hiragana: "", meaning: "접다, 개다" },
  { kanji: "たつ", hiragana: "", meaning: "지나다, 시간이 지나다, 세월이 지나다" },
  { kanji: "調子", hiragana: "ちょうし", meaning: "상태, 컨디션" },
  { kanji: "閉じる", hiragana: "とじる", meaning: "닫다, 감다" },
  { kanji: "突然", hiragana: "とつぜん", meaning: "돌연, 갑자기" },
  { kanji: "引き受ける", hiragana: "ひきうける", meaning: "떠맡다" },
  { kanji: "不安", hiragana: "ふあん", meaning: "불안" },
  { kanji: "物価", hiragana: "ぶっか", meaning: "물가" },
  { kanji: "別々", hiragana: "べつべつ", meaning: "따로따로, 각각" },
  { kanji: "ゆるい", hiragana: "", meaning: "헐렁하다, 느슨하다" },
  { kanji: "意志", hiragana: "いし", meaning: "의지" },
  { kanji: "応援", hiragana: "おうえん", meaning: "응원" },
  { kanji: "起きる", hiragana: "おきる", meaning: "기상하다, 발생하다" },
  { kanji: "外食", hiragana: "がいしょく", meaning: "외식" },
  { kanji: "がっかり", hiragana: "", meaning: "실망, 낙담하는 모양" },
  { kanji: "片方", hiragana: "かたほう", meaning: "한 쪽, 한 짝" },
  { kanji: "カバー", hiragana: "", meaning: "덮개, 커버" },
  { kanji: "枯れる", hiragana: "かれる", meaning: "마르다, 시들다" },
  { kanji: "期待", hiragana: "きたい", meaning: "기대" },
  { kanji: "~差", hiragana: "さ", meaning: "~차, 차" },
  { kanji: "しつこい", hiragana: "", meaning: "끈질기다" },
  { kanji: "自動的", hiragana: "じどうてき", meaning: "자동적" },
  { kanji: "代金", hiragana: "だいきん", meaning: "대금" },
  { kanji: "流れ", hiragana: "ながれ", meaning: "흐름" },
  { kanji: "懐かしい", hiragana: "なつかしい", meaning: "그립다" },
  { kanji: "延ばす", hiragana: "のばす", meaning: "연기하다, 연장하다" },
  { kanji: "振る", hiragana: "ふる", meaning: "흔들다" },
  { kanji: "むく", hiragana: "", meaning: "벗기다, 까다" },
  { kanji: "別れる", hiragana: "わかれる", meaning: "헤어지다, 작별하다" },
  { kanji: "合わせる", hiragana: "あわせる", meaning: "맞추다, 마음을 합치다" },
  { kanji: "インタビュー", hiragana: "", meaning: "인터뷰" },
  { kanji: "影響", hiragana: "えいきょう", meaning: "영향" },
  { kanji: "カーブ", hiragana: "", meaning: "커브" },
  { kanji: "かかる", hiragana: "", meaning: "걸리다, 병에 걸리다" },
  { kanji: "からから", hiragana: "", meaning: "바싹 마른 모양" },
  { kanji: "~産", hiragana: "さん", meaning: "~산, 산" },
  { kanji: "主張", hiragana: "しゅちょう", meaning: "주장" },
  { kanji: "出張", hiragana: "しゅっちょう", meaning: "출장" },
  { kanji: "冗談", hiragana: "じょうだん", meaning: "농담" },
  { kanji: "清潔", hiragana: "せいけつ", meaning: "청결" },
  { kanji: "整理", hiragana: "せいり", meaning: "정리" },
  { kanji: "前後", hiragana: "ぜんご", meaning: "전후" },
  { kanji: "貯める", hiragana: "ためる", meaning: "모으다, 돈을 모으다" },
  { kanji: "流れる", hiragana: "ながれる", meaning: "흐르다" },
  { kanji: "複雑だ", hiragana: "ふくざつだ", meaning: "복잡하다" },
  { kanji: "不満", hiragana: "ふまん", meaning: "불만" },
  { kanji: "ぶらぶら", hiragana: "", meaning: "어슬렁어슬렁, 빈둥빈둥" },
  { kanji: "申込書", hiragana: "もうしこみしょ", meaning: "신청서" },
  { kanji: "両替", hiragana: "りょうがえ", meaning: "환전" },
  { kanji: "扱う", hiragana: "あつかう", meaning: "취급하다" },
  { kanji: "泡", hiragana: "あわ", meaning: "거품" },
  { kanji: "カタログ", hiragana: "", meaning: "카탈로그" },
  { kanji: "感じ", hiragana: "かんじ", meaning: "느낌" },
  { kanji: "感動", hiragana: "かんどう", meaning: "감동" },
  { kanji: "希望", hiragana: "きぼう", meaning: "희망" },
  { kanji: "最新", hiragana: "さいしん", meaning: "최신" },
  { kanji: "しばらく", hiragana: "", meaning: "한동안, 오랫동안" },
  { kanji: "縛る", hiragana: "しばる", meaning: "묶다" },
  { kanji: "しまう", hiragana: "", meaning: "안에 넣다, 치우다" },
  { kanji: "体力", hiragana: "たいりょく", meaning: "체력" },
  { kanji: "早めに", hiragana: "はやめに", meaning: "빨리, 일찌감치" },
  { kanji: "半日", hiragana: "はんにち", meaning: "반일, 반나절" },
  { kanji: "迷う", hiragana: "まよう", meaning: "망설이다, 헤매다" },
  { kanji: "~向き", hiragana: "むき", meaning: "~용, 용" },
  { kanji: "家賃", hiragana: "やちん", meaning: "집세" },
  { kanji: "立派だ", hiragana: "りっぱだ", meaning: "훌륭하다" },
];
