// lib/words_05.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_05: Word[] = [
  { kanji: "あくび", hiragana: "", meaning: "하품" },
  { kanji: "うっかり", hiragana: "", meaning: "깜빡" },
  { kanji: "お互いに", hiragana: "おたがいに", meaning: "서로" },
  { kanji: "可能", hiragana: "かのう", meaning: "가능" },
  { kanji: "感覚", hiragana: "かんかく", meaning: "감각" },
  { kanji: "期限", hiragana: "きげん", meaning: "기한" },
  { kanji: "きちんと", hiragana: "", meaning: "깔끔히" },
  { kanji: "効果的", hiragana: "こうかてき", meaning: "효과적" },
  { kanji: "差", hiragana: "さ", meaning: "차, 차이" },
  { kanji: "制限", hiragana: "せいげん", meaning: "제한" },
  { kanji: "想像", hiragana: "そうぞう", meaning: "상상" },
  { kanji: "だるい", hiragana: "", meaning: "나른하다" },
  { kanji: "付き合う", hiragana: "つきあう", meaning: "사귀다" },
  { kanji: "テーマ", hiragana: "", meaning: "테마" },
  { kanji: "なめる", hiragana: "", meaning: "핥다" },
  { kanji: "番", hiragana: "ばん", meaning: "차례" },
  { kanji: "ヒント", hiragana: "", meaning: "힌트" },
  { kanji: "振る", hiragana: "ふる", meaning: "흔들다" },
  { kanji: "平気だ", hiragana: "へいきだ", meaning: "괜찮다" },
  { kanji: "面倒くさい", hiragana: "めんどうくさい", meaning: "귀찮다" },
  { kanji: "追い越す", hiragana: "おいこす", meaning: "앞지르다, 추월하다" },
  { kanji: "渇く", hiragana: "かわく", meaning: "마르다" },
  { kanji: "希望", hiragana: "きぼう", meaning: "희망" },
  { kanji: "キャンセル", hiragana: "", meaning: "취소" },
  { kanji: "偶然", hiragana: "ぐうぜん", meaning: "우연히" },
  { kanji: "悔しい", hiragana: "くやしい", meaning: "분하다" },
  { kanji: "資源", hiragana: "しげん", meaning: "자원" },
  { kanji: "しみ", hiragana: "", meaning: "얼룩" },
  { kanji: "親戚", hiragana: "しんせき", meaning: "친척" },
  { kanji: "ずきずき", hiragana: "", meaning: "욱신욱신" },
  { kanji: "たたく", hiragana: "", meaning: "두드리다" },
  { kanji: "登場", hiragana: "とうじょう", meaning: "등장" },
  { kanji: "どきどき", hiragana: "", meaning: "두근두근" },
  { kanji: "話し合う", hiragana: "はなしあう", meaning: "의논하다" },
  { kanji: "ぴったり", hiragana: "", meaning: "꼭 맞는 모양, 딱" },
  { kanji: "防ぐ", hiragana: "ふせぐ", meaning: "막다" },
  { kanji: "べつべつ", hiragana: "", meaning: "따로따로" },
  { kanji: "ほえる", hiragana: "", meaning: "짖다" },
  { kanji: "干す", hiragana: "ほす", meaning: "말리다" },
  { kanji: "迷う", hiragana: "まよう", meaning: "망설이다, 헤매다" },
  { kanji: "むく", hiragana: "", meaning: "벗기다" },
  { kanji: "レシピ", hiragana: "", meaning: "레시피, 조리법" },
  { kanji: "意志", hiragana: "いし", meaning: "의지" },
  { kanji: "延期", hiragana: "えんき", meaning: "연기, 기한을 뒤로 늘림" },
  { kanji: "おつかれさま", hiragana: "", meaning: "수고하십니다, 수고하셨습니다" },
  { kanji: "枯れる", hiragana: "かれる", meaning: "시들다" },
  { kanji: "効果", hiragana: "こうか", meaning: "효과" },
  { kanji: "このあいだ", hiragana: "", meaning: "일전, 요전" },
  { kanji: "材料", hiragana: "ざいりょう", meaning: "재료" },
  { kanji: "者", hiragana: "しゃ", meaning: "자" },
  { kanji: "渋滞", hiragana: "じゅうたい", meaning: "정체" },
  { kanji: "セット", hiragana: "", meaning: "세트, 조절" },
  { kanji: "チャレンジ", hiragana: "", meaning: "챌린지, 도전" },
  { kanji: "土地", hiragana: "とち", meaning: "토지, 땅" },
  { kanji: "なるべく", hiragana: "", meaning: "되도록" },
  { kanji: "ばらばら", hiragana: "", meaning: "제각각, 제각기" },
  { kanji: "ぺらぺら", hiragana: "", meaning: "줄줄, 술술" },
  { kanji: "報告", hiragana: "ほうこく", meaning: "보고" },
  { kanji: "身につける", hiragana: "みにつける", meaning: "익히다" },
  { kanji: "無駄", hiragana: "むだ", meaning: "낭비, 헛됨" },
  { kanji: "もったいない", hiragana: "", meaning: "아깝다" },
  { kanji: "翌日", hiragana: "よくじつ", meaning: "익일, 다음날" },
  { kanji: "囲む", hiragana: "かこむ", meaning: "둘러싸다, 에워싸다" },
  { kanji: "配達", hiragana: "はいたつ", meaning: "배달" },
  { kanji: "比較", hiragana: "ひかく", meaning: "비교" },
  { kanji: "引き受ける", hiragana: "ひきうける", meaning: "맡다" },
  { kanji: "文句", hiragana: "もんく", meaning: "불만, 불평" },
  { kanji: "ユーモア", hiragana: "", meaning: "유머" },
  { kanji: "うろうろ", hiragana: "", meaning: "허둥지둥" },
  { kanji: "間隔", hiragana: "かんかく", meaning: "간격" },
  { kanji: "芸術", hiragana: "げいじゅつ", meaning: "예술" },
  { kanji: "さっそく", hiragana: "", meaning: "즉시" },
  { kanji: "しまう", hiragana: "", meaning: "치우다" },
  { kanji: "締め切り", hiragana: "しめきり", meaning: "마감" },
  { kanji: "就職", hiragana: "しゅうしょく", meaning: "취직" },
  { kanji: "冗談", hiragana: "じょうだん", meaning: "농담" },
  { kanji: "清潔", hiragana: "せいけつ", meaning: "청결" },
  { kanji: "積極的", hiragana: "せっきょくてき", meaning: "적극적" },
  { kanji: "通訳", hiragana: "つうやく", meaning: "통역" },
  { kanji: "デザイン", hiragana: "", meaning: "디자인" },
  { kanji: "溶ける", hiragana: "とける", meaning: "녹다" },
  { kanji: "突然", hiragana: "とつぜん", meaning: "돌연" },
  { kanji: "取り消す", hiragana: "とりけす", meaning: "취소하다" },
  { kanji: "ノック", hiragana: "", meaning: "노크" },
  { kanji: "あふれる", hiragana: "", meaning: "넘치다" },
  { kanji: "意外に", hiragana: "いがいに", meaning: "의외로" },
  { kanji: "エネルギー", hiragana: "", meaning: "에너지" },
  { kanji: "乾燥", hiragana: "かんそう", meaning: "건조" },
  { kanji: "きつい", hiragana: "", meaning: "끼다" },
  { kanji: "しっかり", hiragana: "", meaning: "꽉, 단단히" },
  { kanji: "自動的に", hiragana: "じどうてきに", meaning: "자동적으로" },
  { kanji: "絞る", hiragana: "しぼる", meaning: "짜다, 물기를 빼다" },
  { kanji: "発展", hiragana: "はってん", meaning: "발전" },
  { kanji: "交ざる", hiragana: "まざる", meaning: "섞이다" },
  { kanji: "待ち合わせる", hiragana: "まちあわせる", meaning: "만나기로 하다" },
  { kanji: "目標", hiragana: "もくひょう", meaning: "목표" },
  { kanji: "落ち着く", hiragana: "おちつく", meaning: "가라앉다, 침착하다" },
  { kanji: "確実だ", hiragana: "かくじつだ", meaning: "확실하다" },
  { kanji: "申請", hiragana: "しんせい", meaning: "신청" },
  { kanji: "ずいぶん", hiragana: "", meaning: "꽤, 상당히" },
  { kanji: "底", hiragana: "そこ", meaning: "바닥, 속" },
  { kanji: "そっくり", hiragana: "", meaning: "꼭 닮음" },
  { kanji: "そっと", hiragana: "", meaning: "살짝" },
  { kanji: "拭く", hiragana: "ふく", meaning: "닦다" },
  { kanji: "マナー", hiragana: "", meaning: "매너" },
  { kanji: "目的", hiragana: "もくてき", meaning: "목적" },
  { kanji: "床", hiragana: "ゆか", meaning: "마루" },
  { kanji: "呼び掛ける", hiragana: "よびかける", meaning: "호소하다" },
  { kanji: "列", hiragana: "れつ", meaning: "열, 행렬" },
  { kanji: "アドバイス", hiragana: "", meaning: "충고" },
  { kanji: "イメージ", hiragana: "", meaning: "이미지" },
  { kanji: "うまい", hiragana: "", meaning: "맛있다, 솜씨가 좋다" },
  { kanji: "噂", hiragana: "うわさ", meaning: "소문" },
  { kanji: "惜しい", hiragana: "おしい", meaning: "아깝다" },
  { kanji: "がらがら", hiragana: "", meaning: "텅텅 빈 모양" },
  { kanji: "傷", hiragana: "きず", meaning: "상처, 흠" },
  { kanji: "沈む", hiragana: "しずむ", meaning: "가라앉다, 지다" },
  { kanji: "姿勢", hiragana: "しせい", meaning: "자세" },
  { kanji: "確かめる", hiragana: "たしかめる", meaning: "확인하다" },
  { kanji: "頼る", hiragana: "たよる", meaning: "의지하다" },
  { kanji: "特長", hiragana: "とくちょう", meaning: "특별한 장점" },
  { kanji: "内緒", hiragana: "ないしょ", meaning: "비밀, 은밀" },
  { kanji: "農業", hiragana: "のうぎょう", meaning: "농업" },
  { kanji: "許す", hiragana: "ゆるす", meaning: "용서하다, 허락하다" },
  { kanji: "流行している", hiragana: "りゅうこうしている", meaning: "유행하고 있다" },
];