// lib/words_02.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_02: Word[] = [
  { kanji: "表す", hiragana: "あらわす", meaning: "나타내다" },
  { kanji: "美しい", hiragana: "うつくしい", meaning: "아름답다" },
  { kanji: "首", hiragana: "くび", meaning: "목" },
  { kanji: "経営学", hiragana: "けいえいがく", meaning: "경영학" },
  { kanji: "血液型", hiragana: "けつえきがた", meaning: "혈액형" },
  { kanji: "支給", hiragana: "しきゅう", meaning: "지급" },
  { kanji: "想像", hiragana: "そうぞう", meaning: "상상" },
  { kanji: "朝食", hiragana: "ちょうしょく", meaning: "조식, 아침 식사" },
  { kanji: "伝える", hiragana: "つたえる", meaning: "전하다" },
  { kanji: "荷物", hiragana: "にもつ", meaning: "짐, 화물" },
  { kanji: "分類", hiragana: "ぶんるい", meaning: "분류" },
  { kanji: "平均", hiragana: "へいきん", meaning: "평균" },
  { kanji: "変化", hiragana: "へんか", meaning: "변화" },
  { kanji: "干す", hiragana: "ほす", meaning: "말리다" },
  { kanji: "湖", hiragana: "みずうみ", meaning: "호수" },
  { kanji: "汚れる", hiragana: "よごれる", meaning: "더러워지다" },
  { kanji: "相手", hiragana: "あいて", meaning: "상대" },
  { kanji: "厚い", hiragana: "あつい", meaning: "두껍다" },
  { kanji: "一般的だ", hiragana: "いっぱんてきだ", meaning: "일반적이다" },
  { kanji: "応用", hiragana: "おうよう", meaning: "응용" },
  { kanji: "覚える", hiragana: "おぼえる", meaning: "기억하다, 외우다" },
  { kanji: "替える", hiragana: "かえる", meaning: "바꾸다, 교환하다" },
  { kanji: "検査", hiragana: "けんさ", meaning: "검사" },
  { kanji: "広告", hiragana: "こうこく", meaning: "광고" },
  { kanji: "集中", hiragana: "しゅうちゅう", meaning: "집중" },
  { kanji: "商業", hiragana: "しょうぎょう", meaning: "상업" },
  { kanji: "食器", hiragana: "しょっき", meaning: "식기" },
  { kanji: "大会", hiragana: "たいかい", meaning: "대회" },
  { kanji: "横", hiragana: "よこ", meaning: "옆, 가로" },
  { kanji: "割れる", hiragana: "われる", meaning: "갈라지다, 깨지다" },
  { kanji: "浅い", hiragana: "あさい", meaning: "얕다" },
  { kanji: "各地", hiragana: "かくち", meaning: "각지" },
  { kanji: "苦しい", hiragana: "くるしい", meaning: "괴롭다, 난처하다" },
  { kanji: "事情", hiragana: "じじょう", meaning: "사정" },
  { kanji: "実力", hiragana: "じつりょく", meaning: "실력" },
  { kanji: "出張", hiragana: "しゅっちょう", meaning: "출장" },
  { kanji: "席", hiragana: "せき", meaning: "자리" },
  { kanji: "貯金", hiragana: "ちょきん", meaning: "저금" },
  { kanji: "根", hiragana: "ね", meaning: "뿌리" },
  { kanji: "文章", hiragana: "ぶんしょう", meaning: "문장" },
  { kanji: "笑う", hiragana: "わらう", meaning: "웃다" },
  { kanji: "合図", hiragana: "あいず", meaning: "신호, 눈짓, 몸짓" },
  { kanji: "汗", hiragana: "あせ", meaning: "땀" },
  { kanji: "以降", hiragana: "いこう", meaning: "이후" },
  { kanji: "笑顔", hiragana: "えがお", meaning: "웃는 얼굴" },
  { kanji: "固い", hiragana: "かたい", meaning: "단단하다, 굳다" },
  { kanji: "完成", hiragana: "かんせい", meaning: "완성" },
  { kanji: "配る", hiragana: "くばる", meaning: "분배하다, 배포하다" },
  { kanji: "外科", hiragana: "げか", meaning: "외과" },
  { kanji: "困る", hiragana: "こまる", meaning: "곤란하다" },
  { kanji: "島", hiragana: "しま", meaning: "섬" },
  { kanji: "示す", hiragana: "しめす", meaning: "가리키다, 보이다, 나타내다" },
  { kanji: "他人", hiragana: "たにん", meaning: "타인" },
  { kanji: "平日", hiragana: "へいじつ", meaning: "평일" },
  { kanji: "短い", hiragana: "みじかい", meaning: "짧다" },
  { kanji: "応募", hiragana: "おうぼ", meaning: "응모" },
  { kanji: "遅れる", hiragana: "おくれる", meaning: "늦다" },
  { kanji: "折る", hiragana: "おる", meaning: "접다, 꺾다" },
  { kanji: "返す", hiragana: "かえす", meaning: "돌리다, 돌려주다" },
  { kanji: "価格", hiragana: "かかく", meaning: "가격" },
  { kanji: "疑問", hiragana: "ぎもん", meaning: "의문" },
  { kanji: "協力", hiragana: "きょうりょく", meaning: "협력" },
  { kanji: "首都", hiragana: "しゅと", meaning: "수도" },
  { kanji: "単語", hiragana: "たんご", meaning: "단어" },
  { kanji: "地球", hiragana: "ちきゅう", meaning: "지구" },
  { kanji: "発表", hiragana: "はっぴょう", meaning: "발표" },
  { kanji: "表面", hiragana: "ひょうめん", meaning: "표면" },
  { kanji: "深い", hiragana: "ふかい", meaning: "깊다" },
  { kanji: "息", hiragana: "いき", meaning: "숨" },
  { kanji: "移す", hiragana: "うつす", meaning: "옮기다" },
  { kanji: "空席", hiragana: "くうせき", meaning: "공석" },
  { kanji: "組む", hiragana: "くむ", meaning: "짜다, 편성하다" },
  { kanji: "苦労", hiragana: "くろう", meaning: "고생" },
  { kanji: "失業", hiragana: "しつぎょう", meaning: "실업, 실직" },
  { kanji: "順番", hiragana: "じゅんばん", meaning: "순번, 차례" },
  { kanji: "通勤", hiragana: "つうきん", meaning: "통근" },
  { kanji: "発見", hiragana: "はっけん", meaning: "발견" },
];