// lib/words_01.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_01: Word[] = [
  { kanji: "疑う", hiragana: "うたがう", meaning: "의심하다" },
  { kanji: "裏", hiragana: "うら", meaning: "뒤, 뒤쪽" },
  { kanji: "月末", hiragana: "げつまつ", meaning: "월말" },
  { kanji: "高価", hiragana: "こうか", meaning: "고가" },
  { kanji: "小型", hiragana: "こがた", meaning: "소형" },
  { kanji: "断る", hiragana: "ことわる", meaning: "거절하다" },
  { kanji: "産業", hiragana: "さんぎょう", meaning: "산업" },
  { kanji: "選手", hiragana: "せんしゅ", meaning: "선수" },
  { kanji: "退院", hiragana: "たいいん", meaning: "퇴원" },
  { kanji: "朝刊", hiragana: "ちょうかん", meaning: "조간" },
  { kanji: "広場", hiragana: "ひろば", meaning: "광장" },
  { kanji: "夫婦", hiragana: "ふうふ", meaning: "부부" },
  { kanji: "復習", hiragana: "ふくしゅう", meaning: "복습" },
  { kanji: "細い", hiragana: "ほそい", meaning: "좁다" },
  { kanji: "汚す", hiragana: "よごす", meaning: "더럽히다" },
  { kanji: "留守", hiragana: "るす", meaning: "부재중" },
  { kanji: "横断", hiragana: "おうだん", meaning: "횡단" },
  { kanji: "角", hiragana: "かど", meaning: "모퉁이" },
  { kanji: "比べる", hiragana: "くらべる", meaning: "비교하다" },
  { kanji: "計算", hiragana: "けいさん", meaning: "계산" },
  { kanji: "血圧", hiragana: "けつあつ", meaning: "혈압" },
  { kanji: "件", hiragana: "けん", meaning: "건" },
  { kanji: "現在", hiragana: "げんざい", meaning: "현재" },
  { kanji: "情報", hiragana: "じょうほう", meaning: "정보" },
  { kanji: "包む", hiragana: "つつむ", meaning: "싸다, 포장하다" },
  { kanji: "複数", hiragana: "ふくすう", meaning: "복수" },
  { kanji: "丸い", hiragana: "まるい", meaning: "둥글다" },
  { kanji: "難しい", hiragana: "むずかしい", meaning: "어렵다" },
  { kanji: "夕日", hiragana: "ゆうひ", meaning: "석양" },
  { kanji: "有名だ", hiragana: "ゆうめいだ", meaning: "유명하다" },
  { kanji: "容器", hiragana: "ようき", meaning: "용기" },
  { kanji: "過去", hiragana: "かこ", meaning: "과거" },
  { kanji: "悲しい", hiragana: "かなしい", meaning: "슬프다" },
  { kanji: "恋しい", hiragana: "こいしい", meaning: "그립다" },
  { kanji: "呼吸", hiragana: "こきゅう", meaning: "호흡" },
  { kanji: "自然", hiragana: "しぜん", meaning: "자연" },
  { kanji: "増減", hiragana: "ぞうげん", meaning: "증감" },
  { kanji: "駐車", hiragana: "ちゅうしゃ", meaning: "주차" },
  { kanji: "通知", hiragana: "つうち", meaning: "통지" },
  { kanji: "動作", hiragana: "どうさ", meaning: "동작" },
  { kanji: "努力", hiragana: "どりょく", meaning: "노력" },
  { kanji: "逃げる", hiragana: "にげる", meaning: "도망치다, 달아나다" },
  { kanji: "残り", hiragana: "のこり", meaning: "나머지" },
  { kanji: "生える", hiragana: "はえる", meaning: "나다, 자라다" },
  { kanji: "秒", hiragana: "びょう", meaning: "초" },
  { kanji: "郵送", hiragana: "ゆうそう", meaning: "우송" },
  { kanji: "預ける", hiragana: "あずける", meaning: "맡기다" },
  { kanji: "岩", hiragana: "いわ", meaning: "바위" },
  { kanji: "交流", hiragana: "こうりゅう", meaning: "교류" },
  { kanji: "種類", hiragana: "しゅるい", meaning: "종류" },
  { kanji: "調査", hiragana: "ちょうさ", meaning: "조사" },
  { kanji: "普通", hiragana: "ふつう", meaning: "보통, 대개" },
  { kanji: "印象", hiragana: "いんしょう", meaning: "인상" },
  { kanji: "遅い", hiragana: "おそい", meaning: "늦다, 느리다" },
  { kanji: "各駅", hiragana: "かくえき", meaning: "각 역" },
  { kanji: "勝つ", hiragana: "かつ", meaning: "이기다" },
  { kanji: "腰", hiragana: "こし", meaning: "허리" },
  { kanji: "上品だ", hiragana: "じょうひんだ", meaning: "고상하다" },
  { kanji: "線", hiragana: "せん", meaning: "선" },
  { kanji: "助ける", hiragana: "たすける", meaning: "돕다, 살리다" },
  { kanji: "昼食", hiragana: "ちゅうしょく", meaning: "중식, 점심 식사" },
  { kanji: "方角", hiragana: "ほうがく", meaning: "방위, 방향" },
  { kanji: "未来", hiragana: "みらい", meaning: "미래" },
  { kanji: "郵便", hiragana: "ゆうびん", meaning: "우편" },
  { kanji: "予約", hiragana: "よやく", meaning: "예약" },
  { kanji: "若い", hiragana: "わかい", meaning: "젊다" },
  { kanji: "遊ぶ", hiragana: "あそぶ", meaning: "놀다" },
  { kanji: "改札", hiragana: "かいさつ", meaning: "개찰, 개찰구" },
  { kanji: "換える", hiragana: "かえる", meaning: "바꾸다" },
  { kanji: "機械", hiragana: "きかい", meaning: "기계" },
  { kanji: "休日", hiragana: "きゅうじつ", meaning: "휴일" },
  { kanji: "塩", hiragana: "しお", meaning: "소금" },
  { kanji: "制服", hiragana: "せいふく", meaning: "제복" },
  { kanji: "相談", hiragana: "そうだん", meaning: "상담, 상의" },
  { kanji: "卒業", hiragana: "そつぎょう", meaning: "졸업" },
  { kanji: "確かに", hiragana: "たしかに", meaning: "확실히" },
  { kanji: "得意だ", hiragana: "とくいだ", meaning: "자신이 있다" },
  { kanji: "部分", hiragana: "ぶぶん", meaning: "부분" },
  { kanji: "命令", hiragana: "めいれい", meaning: "명령" },
  { kanji: "位置", hiragana: "いち", meaning: "위치" },
  { kanji: "下線", hiragana: "かせん", meaning: "밑줄" },
  { kanji: "汚い", hiragana: "きたない", meaning: "더럽다" },
  { kanji: "禁煙", hiragana: "きんえん", meaning: "금연" },
  { kanji: "転ぶ", hiragana: "ころぶ", meaning: "넘어지다" },
  { kanji: "手術", hiragana: "しゅじゅつ", meaning: "수술" },
  { kanji: "主要だ", hiragana: "しゅようだ", meaning: "주요하다" },
  { kanji: "商品", hiragana: "しょうひん", meaning: "상품" },
  { kanji: "早退", hiragana: "そうたい", meaning: "조퇴" },
  { kanji: "直接", hiragana: "ちょくせつ", meaning: "직접" },
  { kanji: "冷える", hiragana: "ひえる", meaning: "차가워지다, 식다" },
  { kanji: "回す", hiragana: "まわす", meaning: "돌리다, 회전시키다" },
  { kanji: "結ぶ", hiragana: "むすぶ", meaning: "잇다, 매다, 묶다" },
  { kanji: "燃える", hiragana: "もえる", meaning: "타다" },
  { kanji: "折れる", hiragana: "おれる", meaning: "부러지다, 꺾이다" },
  { kanji: "観客", hiragana: "かんきゃく", meaning: "관객" },
  { kanji: "共通", hiragana: "きょうつう", meaning: "공통" },
  { kanji: "加える", hiragana: "くわえる", meaning: "더하다, 보태다" },
  { kanji: "訓練", hiragana: "くんれん", meaning: "훈련" },
  { kanji: "個人", hiragana: "こじん", meaning: "개인" },
  { kanji: "税金", hiragana: "ぜいきん", meaning: "세금" },
  { kanji: "到着", hiragana: "とうちゃく", meaning: "도착" },
  { kanji: "独立", hiragana: "どくりつ", meaning: "독립" },
  { kanji: "測る", hiragana: "はかる", meaning: "재다, 달다" },
  { kanji: "払う", hiragana: "はらう", meaning: "내다, 지불하다" },
  { kanji: "方向", hiragana: "ほうこう", meaning: "방향" },
  { kanji: "豆", hiragana: "まめ", meaning: "콩" },
  { kanji: "申し込み", hiragana: "もうしこみ", meaning: "신청" },
];
