// lib/words_04.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_04: Word[] = [
  { kanji: "楽器", hiragana: "がっき", meaning: "악기" },
  { kanji: "借りる", hiragana: "かりる", meaning: "빌리다" },
  { kanji: "関心", hiragana: "かんしん", meaning: "관심" },
  { kanji: "規則", hiragana: "きそく", meaning: "규칙" },
  { kanji: "欠点", hiragana: "けってん", meaning: "결점" },
  { kanji: "原因", hiragana: "げんいん", meaning: "원인" },
  { kanji: "現在", hiragana: "げんざい", meaning: "현재" },
  { kanji: "正解", hiragana: "せいかい", meaning: "정답" },
  { kanji: "勤める", hiragana: "つとめる", meaning: "근무하다" },
  { kanji: "投げる", hiragana: "なげる", meaning: "던지다" },
  { kanji: "願う", hiragana: "ねがう", meaning: "바라다, 원하다" },
  { kanji: "緑", hiragana: "みどり", meaning: "녹색" },
  { kanji: "移る", hiragana: "うつる", meaning: "옮기다, 이동하다" },
  { kanji: "温泉", hiragana: "おんせん", meaning: "온천" },
  { kanji: "仮定", hiragana: "かてい", meaning: "가정, 상정" },
  { kanji: "消す", hiragana: "けす", meaning: "끄다" },
  { kanji: "欠席", hiragana: "けっせき", meaning: "결석" },
  { kanji: "減少", hiragana: "げんしょう", meaning: "감소" },
  { kanji: "恋しい", hiragana: "こいしい", meaning: "그립다" },
  { kanji: "細かい", hiragana: "こまかい", meaning: "잘다, 작다" },
  { kanji: "雑誌", hiragana: "ざっし", meaning: "잡지" },
  { kanji: "駐車", hiragana: "ちゅうしゃ", meaning: "주차" },
  { kanji: "複数", hiragana: "ふくすう", meaning: "복수" },
  { kanji: "若い", hiragana: "わかい", meaning: "젊다" },
  { kanji: "遅い", hiragana: "おそい", meaning: "늦다" },
  { kanji: "重ねる", hiragana: "かさねる", meaning: "겹치다, 포개다" },
  { kanji: "貸す", hiragana: "かす", meaning: "빌려주다" },
  { kanji: "残業", hiragana: "ざんぎょう", meaning: "잔업" },
  { kanji: "信じる", hiragana: "しんじる", meaning: "믿다" },
  { kanji: "疲れる", hiragana: "つかれる", meaning: "지치다, 피곤하다" },
  { kanji: "包む", hiragana: "つつむ", meaning: "포장하다, 감싸다" },
  { kanji: "停電", hiragana: "ていでん", meaning: "정전" },
  { kanji: "独身", hiragana: "どくしん", meaning: "독신" },
  { kanji: "逃げる", hiragana: "にげる", meaning: "도망치다" },
  { kanji: "倍", hiragana: "ばい", meaning: "배, ~배" },
  { kanji: "容器", hiragana: "ようき", meaning: "용기, 그릇" },
  { kanji: "温める", hiragana: "あたためる", meaning: "따뜻하게 하다, 데우다" },
  { kanji: "帰宅", hiragana: "きたく", meaning: "귀가" },
  { kanji: "記録", hiragana: "きろく", meaning: "기록" },
  { kanji: "原料", hiragana: "げんりょう", meaning: "원료" },
  { kanji: "自信", hiragana: "じしん", meaning: "자신, 자신감" },
  { kanji: "週刊誌", hiragana: "しゅうかんし", meaning: "주간지" },
  { kanji: "相談", hiragana: "そうだん", meaning: "상담, 의논" },
  { kanji: "育てる", hiragana: "そだてる", meaning: "키우다, 기르다" },
  { kanji: "歯", hiragana: "は", meaning: "이, 이빨" },
  { kanji: "復習", hiragana: "ふくしゅう", meaning: "복습" },
  { kanji: "守る", hiragana: "まもる", meaning: "지키다, 보호하다" },
  { kanji: "結ぶ", hiragana: "むすぶ", meaning: "잇다, 묶다" },
  { kanji: "案内", hiragana: "あんない", meaning: "안내" },
  { kanji: "痛い", hiragana: "いたい", meaning: "아프다" },
  { kanji: "解決", hiragana: "かいける", meaning: "해결" },
  { kanji: "観光", hiragana: "かんこう", meaning: "관광" },
  { kanji: "気温", hiragana: "きおん", meaning: "기온" },
  { kanji: "券", hiragana: "けん", meaning: "권, 표" },
  { kanji: "健康", hiragana: "けんこう", meaning: "건강" },
  { kanji: "自由", hiragana: "じゆう", meaning: "자유" },
  { kanji: "大量", hiragana: "たいりょう", meaning: "대량" },
  { kanji: "涙", hiragana: "なみだ", meaning: "눈물" },
  { kanji: "法律", hiragana: "ほうりつ", meaning: "법률" },
  { kanji: "内側", hiragana: "うちがわ", meaning: "안쪽" },
  { kanji: "追う", hiragana: "おう", meaning: "쫓다, 뒤따르다" },
  { kanji: "降りる", hiragana: "おりる", meaning: "내리다" },
  { kanji: "暮らす", hiragana: "くらす", meaning: "살다, 생활하다, 지내다" },
  { kanji: "血液", hiragana: "けつえき", meaning: "혈액" },
  { kanji: "身長", hiragana: "しんちょう", meaning: "신장" },
  { kanji: "正常", hiragana: "せいじょう", meaning: "정상, 제대로 된 상태" },
  { kanji: "成績", hiragana: "せいせき", meaning: "성적" },
  { kanji: "制服", hiragana: "せいふく", meaning: "제복, 교복" },
  { kanji: "専門家", hiragana: "せんもんか", meaning: "전문가" },
  { kanji: "物語", hiragana: "ものがたり", meaning: "이야기" },
];