// lib/words_03.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_03: Word[] = [
  { kanji: "降りる", hiragana: "おりる", meaning: "내리다" },
  { kanji: "会費", hiragana: "かいひ", meaning: "회비" },
  { kanji: "必ず", hiragana: "かならず", meaning: "반드시" },
  { kanji: "空", hiragana: "から", meaning: "속이 빔, 빔" },
  { kanji: "帰宅", hiragana: "きたく", meaning: "귀가" },
  { kanji: "細かい", hiragana: "こまかい", meaning: "작다, 잘다" },
  { kanji: "心配する", hiragana: "しんぱいする", meaning: "걱정하다" },
  { kanji: "制服", hiragana: "せいふく", meaning: "교복" },
  { kanji: "短気だ", hiragana: "たんきだ", meaning: "성질이 급하다" },
  { kanji: "法律", hiragana: "ほうりつ", meaning: "법률" },
  { kanji: "焼く", hiragana: "やく", meaning: "굽다, 태우다" },
  { kanji: "薬局", hiragana: "やっきょく", meaning: "약국" },
  { kanji: "胃", hiragana: "い", meaning: "위, 위장" },
  { kanji: "絵画", hiragana: "かいが", meaning: "회화, 그림" },
  { kanji: "記録", hiragana: "きろく", meaning: "기록" },
  { kanji: "黒板", hiragana: "こくばん", meaning: "칠판" },
  { kanji: "確かだ", hiragana: "たしかだ", meaning: "확실하다" },
  { kanji: "預ける", hiragana: "あずける", meaning: "맡기다" },
  { kanji: "暖かい", hiragana: "あたたかい", meaning: "따뜻하다" },
  { kanji: "重ねる", hiragana: "かさねる", meaning: "포개다, 겹치다" },
  { kanji: "規則", hiragana: "きそく", meaning: "규칙" },
  { kanji: "性格", hiragana: "せいかく", meaning: "성격" },
  { kanji: "伝言", hiragana: "でんごん", meaning: "전언" },
  { kanji: "泊まる", hiragana: "とまる", meaning: "묵다, 숙박하다" },
  { kanji: "娘", hiragana: "むすめ", meaning: "딸" },
  { kanji: "予想", hiragana: "よそう", meaning: "예상" },
  { kanji: "観察", hiragana: "かんさつ", meaning: "관찰" },
  { kanji: "逆", hiragana: "ぎゃく", meaning: "반대, 거꾸로임" },
  { kanji: "泣く", hiragana: "なく", meaning: "울다" },
  { kanji: "低い", hiragana: "ひくい", meaning: "낮다" },
  { kanji: "複雑だ", hiragana: "ふくざつだ", meaning: "복잡하다" },
  { kanji: "現れる", hiragana: "あらわれる", meaning: "나타나다" },
  { kanji: "内側", hiragana: "うちがわ", meaning: "안쪽" },
  { kanji: "家具", hiragana: "かぐ", meaning: "가구" },
  { kanji: "記念", hiragana: "きねん", meaning: "기념" },
  { kanji: "最初", hiragana: "さいしょ", meaning: "최초" },
  { kanji: "停電", hiragana: "ていでん", meaning: "정전" },
  { kanji: "訳する", hiragana: "やくする", meaning: "번역하다" },
  { kanji: "理由", hiragana: "りゆう", meaning: "이유" },
  { kanji: "当たる", hiragana: "あたる", meaning: "맞다" },
  { kanji: "右折", hiragana: "うせつ", meaning: "우회전" },
  { kanji: "週刊誌", hiragana: "しゅうかんし", meaning: "주간지" },
  { kanji: "出勤", hiragana: "しゅっきん", meaning: "출근" },
  { kanji: "疲れ", hiragana: "つかれ", meaning: "피로" },
  { kanji: "熱心だ", hiragana: "ねっしんだ", meaning: "열심이다" },
  { kanji: "関係", hiragana: "かんけい", meaning: "관계" },
  { kanji: "期待", hiragana: "きたい", meaning: "기대" },
  { kanji: "教師", hiragana: "きょうし", meaning: "교사" },
  { kanji: "経由", hiragana: "けいゆ", meaning: "경유" },
  { kanji: "坂道", hiragana: "さかみち", meaning: "비탈길, 언덕길" },
  { kanji: "頭痛", hiragana: "ずつう", meaning: "두통" },
  { kanji: "違う", hiragana: "ちがう", meaning: "다르다" },
  { kanji: "飛ぶ", hiragana: "とぶ", meaning: "날다" },
  { kanji: "葉", hiragana: "は", meaning: "잎, 잎사귀" },
  { kanji: "乗車", hiragana: "じょうしゃ", meaning: "승차" },
  { kanji: "成績", hiragana: "せいせき", meaning: "성적" },
  { kanji: "波", hiragana: "なみ", meaning: "파도, 물결" },
  { kanji: "眠る", hiragana: "ねむる", meaning: "잠자다" },
  { kanji: "速く", hiragana: "はやく", meaning: "빨리" },
  { kanji: "満足", hiragana: "まんぞく", meaning: "만족" },
  { kanji: "輸出", hiragana: "ゆしゅつ", meaning: "수출" },
];